export const PETER_PAN = {
  title: 'Peter Pan',
  author: 'J. M. Barrie',
  chapters: [
    {
      title: 'Chapter — PETER BREAKS THROUGH',
      paragraphs: [
        'All children except one grow up They soon know that they will grow up and the way Wendy knew was this One day when she was two years old she was playing in a garden and she plucked another flower and ran with it to her mother I suppose she must have looked rather delightful for Mrs Darling put her hand to her heart and cried Oh why cant you remain like this for ever This was all that passed between them on the subject but henceforth Wendy knew that she must grow up You always know after you are two Two is the beginning of the end',
        'Of course they lived at 14 and until Wendy came her mother was the chief one She was a lovely lady with a romantic mind and such a sweet mocking mouth Her romantic mind was like the tiny boxes one within the other that come from the puzzling East however many you discover there is always one more and her sweet mocking mouth had one kiss on it that Wendy could never get though there it was perfectly conspicuous in the righthand corner',
        'The way Mr Darling won her was this the many gentlemen who had been boys when she was a girl discovered simultaneously that they loved her and they all ran to her house to propose to her except Mr Darling who took a cab and nipped in first and so he got her He got all of her except the innermost box and the kiss He never knew about the box and in time he gave up trying for the kiss Wendy thought Napoleon could have got it but I can picture him trying and then going off in a passion slamming the door',
        'Mr Darling used to boast to Wendy that her mother not only loved him but respected him He was one of those deep ones who know about stocks and shares Of course no one really knows but he quite seemed to know and he often said stocks were up and shares were down in a way that would have made any woman respect him',
        'Mrs Darling was married in white and at first she kept the books perfectly almost gleefully as if it were a game not so much as a Brussels sprout was missing but by and by whole cauliflowers dropped out and instead of them there were pictures of babies without faces She drew them when she should have been totting up They were Mrs Darlings guesses',
        'Wendy came first then John then Michael',
        'For a week or two after Wendy came it was doubtful whether they would be able to keep her as she was another mouth to feed Mr Darling was frightfully proud of her but he was very honourable and he sat on the edge of Mrs Darlings bed holding her hand and calculating expenses while she looked at him imploringly She wanted to risk it come what might but that was not his way his way was with a pencil and a piece of paper and if she confused him with suggestions he had to begin at the beginning again',
        'Now dont interrupt he would beg of her',
        'I have one pound seventeen here and two and six at the office I can cut off my coffee at the office say ten shillings making two nine and six with your eighteen and three makes three nine seven with five naught naught in my chequebook makes eight nine sevenwho is that movingeight nine seven dot and carry sevendont speak my ownand the pound you lent to that man who came to the doorquiet childdot and carry childthere youve done itdid I say nine nine seven yes I said nine nine seven the question is can we try it for a year on nine nine seven',
        'Of course we can George she cried But she was prejudiced in Wendys favour and he was really the grander character of the two',
        'Remember mumps he warned her almost threateningly and off he went again Mumps one pound that is what I have put down but I daresay it will be more like thirty shillingsdont speakmeasles one five German measles half a guinea makes two fifteen sixdont waggle your fingerwhoopingcough say fifteen shillingsand so on it went and it added up differently each time but at last Wendy just got through with mumps reduced to twelve six and the two kinds of measles treated as one',
        'There was the same excitement over John and Michael had even a narrower squeak but both were kept and soon you might have seen the three of them going in a row to Miss Fulsoms Kindergarten school accompanied by their nurse',
        'Mrs Darling loved to have everything just so and Mr Darling had a passion for being exactly like his neighbours so of course they had a nurse As they were poor owing to the amount of milk the children drank this nurse was a prim Newfoundland dog called Nana who had belonged to no one in particular until the Darlings engaged her She had always thought children important however and the Darlings had become acquainted with her in Kensington Gardens where she spent most of her spare time peeping into perambulators and was much hated by careless nursemaids whom she followed to their homes and complained of to their mistresses She proved to be quite a treasure of a nurse How thorough she was at bathtime and up at any moment of the night if one of her charges made the slightest cry Of course her kennel was in the nursery She had a genius for knowing when a cough is a thing to have no patience with and when it needs stocking around your throat She believed to her last day in oldfashioned remedies like rhubarb leaf and made sounds of contempt over all this newfangled talk about germs and so on It was a lesson in propriety to see her escorting the children to school walking sedately by their side when they were well behaved and butting them back into line if they strayed On Johns footer days she never once forgot his sweater and she usually carried an umbrella in her mouth in case of rain There is a room in the basement of Miss Fulsoms school where the nurses wait They sat on forms while Nana lay on the floor but that was the only difference They affected to ignore her as of an inferior social status to themselves and she despised their light talk She resented visits to the nursery from Mrs Darlings friends but if they did come she first whipped off Michaels pinafore and put him into the one with blue braiding and smoothed out Wendy and made a dash at Johns hair',
        'No nursery could possibly have been conducted more correctly and Mr Darling knew it yet he sometimes wondered uneasily whether the neighbours talked',
        'He had his position in the city to consider',
        'Nana also troubled him in another way He had sometimes a feeling that she did not admire him I know she admires you tremendously George Mrs Darling would assure him and then she would sign to the children to be specially nice to father Lovely dances followed in which the only other servant Liza was sometimes allowed to join Such a midget she looked in her long skirt and maids cap though she had sworn when engaged that she would never see ten again The gaiety of those romps And gayest of all was Mrs Darling who would pirouette so wildly that all you could see of her was the kiss and then if you had dashed at her you might have got it There never was a simpler happier family until the coming of Peter Pan',
        'Mrs Darling first heard of Peter when she was tidying up her childrens minds It is the nightly custom of every good mother after her children are asleep to rummage in their minds and put things straight for next morning repacking into their proper places the many articles that have wandered during the day If you could keep awake but of course you cant you would see your own mother doing this and you would find it very interesting to watch her It is quite like tidying up drawers You would see her on her knees I expect lingering humorously over some of your contents wondering where on earth you had picked this thing up making discoveries sweet and not so sweet pressing this to her cheek as if it were as nice as a kitten and hurriedly stowing that out of sight When you wake in the morning the naughtiness and evil passions with which you went to bed have been folded up small and placed at the bottom of your mind and on the top beautifully aired are spread out your prettier thoughts ready for you to put on',
        'I dont know whether you have ever seen a map of a persons mind Doctors sometimes draw maps of other parts of you and your own map can become intensely interesting but catch them trying to draw a map of a childs mind which is not only confused but keeps going round all the time There are zigzag lines on it just like your temperature on a card and these are probably roads in the island for the Neverland is always more or less an island with astonishing splashes of colour here and there and coral reefs and rakishlooking craft in the offing and savages and lonely lairs and gnomes who are mostly tailors and caves through which a river runs and princes with six elder brothers and a hut fast going to decay and one very small old lady with a hooked nose It would be an easy map if that were all but there is also first day at school religion fathers the round pond needlework murders hangings verbs that take the dative chocolate pudding day getting into braces say ninetynine threepence for pulling out your tooth yourself and so on and either these are part of the island or they are another map showing through and it is all rather confusing especially as nothing will stand still',
        'Of course the Neverlands vary a good deal Johns for instance had a lagoon with flamingoes flying over it at which John was shooting while Michael who was very small had a flamingo with lagoons flying over it John lived in a boat turned upside down on the sands Michael in a wigwam Wendy in a house of leaves deftly sewn together John had no friends Michael had friends at night Wendy had a pet wolf forsaken by its parents but on the whole the Neverlands have a family resemblance and if they stood still in a row you could say of them that they have each others nose and so forth On these magic shores children at play are for ever beaching their coracles We too have been there we can still hear the sound of the surf though we shall land no more',
        'Of all delectable islands the Neverland is the snuggest and most compact not large and sprawly you know with tedious distances between one adventure and another but nicely crammed When you play at it by day with the chairs and tablecloth it is not in the least alarming but in the two minutes before you go to sleep it becomes very real That is why there are nightlights',
        'Occasionally in her travels through her childrens minds Mrs Darling found things she could not understand and of these quite the most perplexing was the word Peter She knew of no Peter and yet he was here and there in John and Michaels minds while Wendys began to be scrawled all over with him The name stood out in bolder letters than any of the other words and as Mrs Darling gazed she felt that it had an oddly cocky appearance',
        'Yes he is rather cocky Wendy admitted with regret Her mother had been questioning her',
        'But who is he my pet',
        'He is Peter Pan you know mother',
        'At first Mrs Darling did not know but after thinking back into her childhood she just remembered a Peter Pan who was said to live with the fairies There were odd stories about him as that when children died he went part of the way with them so that they should not be frightened She had believed in him at the time but now that she was married and full of sense she quite doubted whether there was any such person',
        'Besides she said to Wendy he would be grown up by this time',
        'Oh no he isnt grown up Wendy assured her confidently and he is just my size She meant that he was her size in both mind and body she didnt know how she knew she just knew it',
        'Mrs Darling consulted Mr Darling but he smiled poohpooh Mark my words he said it is some nonsense Nana has been putting into their heads just the sort of idea a dog would have Leave it alone and it will blow over',
        'But it would not blow over and soon the troublesome boy gave Mrs Darling quite a shock',
        'Children have the strangest adventures without being troubled by them For instance they may remember to mention a week after the event happened that when they were in the wood they had met their dead father and had a game with him It was in this casual way that Wendy one morning made a disquieting revelation Some leaves of a tree had been found on the nursery floor which certainly were not there when the children went to bed and Mrs Darling was puzzling over them when Wendy said with a tolerant smile',
        'I do believe it is that Peter again',
        'Whatever do you mean Wendy',
        'It is so naughty of him not to wipe his feet Wendy said sighing She was a tidy child',
        'She explained in quite a matteroffact way that she thought Peter sometimes came to the nursery in the night and sat on the foot of her bed and played on his pipes to her Unfortunately she never woke so she didnt know how she knew she just knew',
        'What nonsense you talk precious No one can get into the house without knocking',
        'I think he comes in by the window she said',
        'My love it is three floors up',
        'Were not the leaves at the foot of the window mother',
        'It was quite true the leaves had been found very near the window',
        'Mrs Darling did not know what to think for it all seemed so natural to Wendy that you could not dismiss it by saying she had been dreaming',
        'My child the mother cried why did you not tell me of this before',
        'I forgot said Wendy lightly She was in a hurry to get her breakfast',
        'Oh surely she must have been dreaming',
        'But on the other hand there were the leaves Mrs Darling examined them very carefully they were skeleton leaves but she was sure they did not come from any tree that grew in England She crawled about the floor peering at it with a candle for marks of a strange foot She rattled the poker up the chimney and tapped the walls She let down a tape from the window to the pavement and it was a sheer drop of thirty feet without so much as a spout to climb up by',
        'Certainly Wendy had been dreaming',
        'But Wendy had not been dreaming as the very next night showed the night on which the extraordinary adventures of these children may be said to have begun',
        'On the night we speak of all the children were once more in bed It happened to be Nanas evening off and Mrs Darling had bathed them and sung to them till one by one they had let go her hand and slid away into the land of sleep',
        'All were looking so safe and cosy that she smiled at her fears now and sat down tranquilly by the fire to sew',
        'It was something for Michael who on his birthday was getting into shirts The fire was warm however and the nursery dimly lit by three nightlights and presently the sewing lay on Mrs Darlings lap Then her head nodded oh so gracefully She was asleep Look at the four of them Wendy and Michael over there John here and Mrs Darling by the fire There should have been a fourth nightlight',
        'While she slept she had a dream She dreamt that the Neverland had come too near and that a strange boy had broken through from it He did not alarm her for she thought she had seen him before in the faces of many women who have no children Perhaps he is to be found in the faces of some mothers also But in her dream he had rent the film that obscures the Neverland and she saw Wendy and John and Michael peeping through the gap',
        'The dream by itself would have been a trifle but while she was dreaming the window of the nursery blew open and a boy did drop on the floor He was accompanied by a strange light no bigger than your fist which darted about the room like a living thing and I think it must have been this light that wakened Mrs Darling',
        'She started up with a cry and saw the boy and somehow she knew at once that he was Peter Pan If you or I or Wendy had been there we should have seen that he was very like Mrs Darlings kiss He was a lovely boy clad in skeleton leaves and the juices that ooze out of trees but the most entrancing thing about him was that he had all his first teeth When he saw she was a grownup he gnashed the little pearls at her',
      ],
    },
    {
      title: 'Chapter — THE SHADOW',
      paragraphs: [
        'Mrs Darling screamed and as if in answer to a bell the door opened and Nana entered returned from her evening out She growled and sprang at the boy who leapt lightly through the window Again Mrs Darling screamed this time in distress for him for she thought he was killed and she ran down into the street to look for his little body but it was not there and she looked up and in the black night she could see nothing but what she thought was a shooting star',
        'She returned to the nursery and found Nana with something in her mouth which proved to be the boys shadow As he leapt at the window Nana had closed it quickly too late to catch him but his shadow had not had time to get out slam went the window and snapped it off',
        'You may be sure Mrs Darling examined the shadow carefully but it was quite the ordinary kind',
        'Nana had no doubt of what was the best thing to do with this shadow She hung it out at the window meaning He is sure to come back for it let us put it where he can get it easily without disturbing the children',
        'But unfortunately Mrs Darling could not leave it hanging out at the window it looked so like the washing and lowered the whole tone of the house She thought of showing it to Mr Darling but he was totting up winter greatcoats for John and Michael with a wet towel around his head to keep his brain clear and it seemed a shame to trouble him besides she knew exactly what he would say It all comes of having a dog for a nurse',
        'She decided to roll the shadow up and put it away carefully in a drawer until a fitting opportunity came for telling her husband Ah me',
        'The opportunity came a week later on that nevertobeforgotten Friday Of course it was a Friday',
        'I ought to have been specially careful on a Friday she used to say afterwards to her husband while perhaps Nana was on the other side of her holding her hand',
        'No no Mr Darling always said I am responsible for it all I George Darling did it Mea culpa mea culpa He had had a classical education',
        'They sat thus night after night recalling that fatal Friday till every detail of it was stamped on their brains and came through on the other side like the faces on a bad coinage',
        'If only I had not accepted that invitation to dine at 27 Mrs Darling said',
        'If only I had not poured my medicine into Nanas bowl said Mr Darling',
        'If only I had pretended to like the medicine was what Nanas wet eyes said',
        'My liking for parties George',
        'My fatal gift of humour dearest',
        'My touchiness about trifles dear master and mistress',
        'Then one or more of them would break down altogether Nana at the thought Its true its true they ought not to have had a dog for a nurse Many a time it was Mr Darling who put the handkerchief to Nanas eyes',
        'That fiend Mr Darling would cry and Nanas bark was the echo of it but Mrs Darling never upbraided Peter there was something in the righthand corner of her mouth that wanted her not to call Peter names',
        'They would sit there in the empty nursery recalling fondly every smallest detail of that dreadful evening It had begun so uneventfully so precisely like a hundred other evenings with Nana putting on the water for Michaels bath and carrying him to it on her back',
        'I wont go to bed he had shouted like one who still believed that he had the last word on the subject I wont I wont Nana it isnt six oclock yet Oh dear oh dear I shant love you any more Nana I tell you I wont be bathed I wont I wont',
        'Then Mrs Darling had come in wearing her white eveninggown She had dressed early because Wendy so loved to see her in her eveninggown with the necklace George had given her She was wearing Wendys bracelet on her arm she had asked for the loan of it Wendy loved to lend her bracelet to her mother',
        'She had found her two older children playing at being herself and father on the occasion of Wendys birth and John was saying',
        'I am happy to inform you Mrs Darling that you are now a mother in just such a tone as Mr Darling himself may have used on the real occasion',
        'Wendy had danced with joy just as the real Mrs Darling must have done',
        'Then John was born with the extra pomp that he conceived due to the birth of a male and Michael came from his bath to ask to be born also but John said brutally that they did not want any more',
        'Michael had nearly cried Nobody wants me he said and of course the lady in the eveningdress could not stand that',
        'I do she said I so want a third child',
        'Boy or girl asked Michael not too hopefully',
        'Then he had leapt into her arms Such a little thing for Mr and Mrs Darling and Nana to recall now but not so little if that was to be Michaels last night in the nursery',
        'They go on with their recollections',
        'It was then that I rushed in like a tornado wasnt it Mr Darling would say scorning himself and indeed he had been like a tornado',
        'Perhaps there was some excuse for him He too had been dressing for the party and all had gone well with him until he came to his tie It is an astounding thing to have to tell but this man though he knew about stocks and shares had no real mastery of his tie Sometimes the thing yielded to him without a contest but there were occasions when it would have been better for the house if he had swallowed his pride and used a madeup tie',
        'This was such an occasion He came rushing into the nursery with the crumpled little brute of a tie in his hand',
        'Why what is the matter father dear',
        'Matter he yelled he really yelled This tie it will not tie He became dangerously sarcastic Not round my neck Round the bedpost Oh yes twenty times have I made it up round the bedpost but round my neck no Oh dear no begs to be excused',
        'He thought Mrs Darling was not sufficiently impressed and he went on sternly I warn you of this mother that unless this tie is round my neck we dont go out to dinner tonight and if I dont go out to dinner tonight I never go to the office again and if I dont go to the office again you and I starve and our children will be flung into the streets',
        'Even then Mrs Darling was placid Let me try dear she said and indeed that was what he had come to ask her to do and with her nice cool hands she tied his tie for him while the children stood around to see their fate decided Some men would have resented her being able to do it so easily but Mr Darling had far too fine a nature for that he thanked her carelessly at once forgot his rage and in another moment was dancing round the room with Michael on his back',
        'How wildly we romped says Mrs Darling now recalling it',
        'Our last romp Mr Darling groaned',
        'O George do you remember Michael suddenly said to me How did you get to know me mother',
        'They were rather sweet dont you think George',
        'And they were ours ours and now they are gone',
        'The romp had ended with the appearance of Nana and most unluckily Mr Darling collided against her covering his trousers with hairs They were not only new trousers but they were the first he had ever had with braid on them and he had had to bite his lip to prevent the tears coming Of course Mrs Darling brushed him but he began to talk again about its being a mistake to have a dog for a nurse',
        'George Nana is a treasure',
        'No doubt but I have an uneasy feeling at times that she looks upon the children as puppies',
        'Oh no dear one I feel sure she knows they have souls',
        'I wonder Mr Darling said thoughtfully I wonder It was an opportunity his wife felt for telling him about the boy At first he poohpoohed the story but he became thoughtful when she showed him the shadow',
        'It is nobody I know he said examining it carefully but it does look a scoundrel',
        'We were still discussing it you remember says Mr Darling when Nana came in with Michaels medicine You will never carry the bottle in your mouth again Nana and it is all my fault',
        'Strong man though he was there is no doubt that he had behaved rather foolishly over the medicine If he had a weakness it was for thinking that all his life he had taken medicine boldly and so now when Michael dodged the spoon in Nanas mouth he had said reprovingly Be a man Michael',
        'Wont wont Michael cried naughtily Mrs Darling left the room to get a chocolate for him and Mr Darling thought this showed want of firmness',
        'Mother dont pamper him he called after her Michael when I was your age I took medicine without a murmur I said Thank you kind parents for giving me bottles to make me well',
        'He really thought this was true and Wendy who was now in her nightgown believed it also and she said to encourage Michael That medicine you sometimes take father is much nastier isnt it',
        'Ever so much nastier Mr Darling said bravely and I would take it now as an example to you Michael if I hadnt lost the bottle',
        'He had not exactly lost it he had climbed in the dead of night to the top of the wardrobe and hidden it there What he did not know was that the faithful Liza had found it and put it back on his washstand',
        'I know where it is father Wendy cried always glad to be of service Ill bring it and she was off before he could stop her Immediately his spirits sank in the strangest way',
        'John he said shuddering its most beastly stuff Its that nasty sticky sweet kind',
        'It will soon be over father John said cheerily and then in rushed Wendy with the medicine in a glass',
        'I have been as quick as I could she panted',
        'You have been wonderfully quick her father retorted with a vindictive politeness that was quite thrown away upon her Michael first he said doggedly',
        'Father first said Michael who was of a suspicious nature',
        'I shall be sick you know Mr Darling said threateningly',
        'Come on father said John',
        'Hold your tongue John his father rapped out',
        'Wendy was quite puzzled I thought you took it quite easily father',
        'That is not the point he retorted The point is that there is more in my glass than in Michaels spoon His proud heart was nearly bursting And it isnt fair I would say it though it were with my last breath it isnt fair',
        'Father I am waiting said Michael coldly',
        'Its all very well to say you are waiting so am I waiting',
        'Fathers a cowardly custard',
        'So are you a cowardly custard',
        'Neither am I frightened',
        'Well then take it',
        'Well then you take it',
        'Wendy had a splendid idea Why not both take it at the same time',
        'Certainly said Mr Darling Are you ready Michael',
        'Wendy gave the words one two three and Michael took his medicine but Mr Darling slipped his behind his back',
        'There was a yell of rage from Michael and O father Wendy exclaimed',
        'What do you mean by O father Mr Darling demanded Stop that row Michael I meant to take mine but II missed it',
        'It was dreadful the way all the three were looking at him just as if they did not admire him Look here all of you he said entreatingly as soon as Nana had gone into the bathroom I have just thought of a splendid joke I shall pour my medicine into Nanas bowl and she will drink it thinking it is milk',
        'It was the colour of milk but the children did not have their fathers sense of humour and they looked at him reproachfully as he poured the medicine into Nanas bowl What fun he said doubtfully and they did not dare expose him when Mrs Darling and Nana returned',
        'Nana good dog he said patting her I have put a little milk into your bowl Nana',
        'Nana wagged her tail ran to the medicine and began lapping it Then she gave Mr Darling such a look not an angry look she showed him the great red tear that makes us so sorry for noble dogs and crept into her kennel',
        'Mr Darling was frightfully ashamed of himself but he would not give in In a horrid silence Mrs Darling smelt the bowl O George she said its your medicine',
        'It was only a joke he roared while she comforted her boys and Wendy hugged Nana Much good he said bitterly my wearing myself to the bone trying to be funny in this house',
        'And still Wendy hugged Nana Thats right he shouted Coddle her Nobody coddles me Oh dear no I am only the breadwinner why should I be coddledwhy why why',
        'George Mrs Darling entreated him not so loud the servants will hear you Somehow they had got into the way of calling Liza the servants',
        'Let them he answered recklessly Bring in the whole world But I refuse to allow that dog to lord it in my nursery for an hour longer',
        'The children wept and Nana ran to him beseechingly but he waved her back He felt he was a strong man again In vain in vain he cried the proper place for you is the yard and there you go to be tied up this instant',
        'George George Mrs Darling whispered remember what I told you about that boy',
        'Alas he would not listen He was determined to show who was master in that house and when commands would not draw Nana from the kennel he lured her out of it with honeyed words and seizing her roughly dragged her from the nursery He was ashamed of himself and yet he did it It was all owing to his too affectionate nature which craved for admiration When he had tied her up in the backyard the wretched father went and sat in the passage with his knuckles to his eyes',
        'In the meantime Mrs Darling had put the children to bed in unwonted silence and lit their nightlights They could hear Nana barking and John whimpered It is because he is chaining her up in the yard but Wendy was wiser',
        'That is not Nanas unhappy bark she said little guessing what was about to happen that is her bark when she smells danger',
        'Are you sure Wendy',
        'Mrs Darling quivered and went to the window It was securely fastened She looked out and the night was peppered with stars They were crowding round the house as if curious to see what was to take place there but she did not notice this nor that one or two of the smaller ones winked at her Yet a nameless fear clutched at her heart and made her cry Oh how I wish that I wasnt going to a party tonight',
        'Even Michael already half asleep knew that she was perturbed and he asked Can anything harm us mother after the nightlights are lit',
        'Nothing precious she said they are the eyes a mother leaves behind her to guard her children',
        'She went from bed to bed singing enchantments over them and little Michael flung his arms round her Mother he cried Im glad of you They were the last words she was to hear from him for a long time',
        'No 27 was only a few yards distant but there had been a slight fall of snow and Father and Mother Darling picked their way over it deftly not to soil their shoes They were already the only persons in the street and all the stars were watching them Stars are beautiful but they may not take an active part in anything they must just look on for ever It is a punishment put on them for something they did so long ago that no star now knows what it was So the older ones have become glassyeyed and seldom speak winking is the star language but the little ones still wonder They are not really friendly to Peter who had a mischievous way of stealing up behind them and trying to blow them out but they are so fond of fun that they were on his side tonight and anxious to get the grownups out of the way So as soon as the door of 27 closed on Mr and Mrs Darling there was a commotion in the firmament and the smallest of all the stars in the Milky Way screamed out',
      ],
    },
    {
      title: 'Chapter — COME AWAY, COME AWAY!',
      paragraphs: [
        'For a moment after Mr and Mrs Darling left the house the nightlights by the beds of the three children continued to burn clearly They were awfully nice little nightlights and one cannot help wishing that they could have kept awake to see Peter but Wendys light blinked and gave such a yawn that the other two yawned also and before they could close their mouths all the three went out',
        'There was another light in the room now a thousand times brighter than the nightlights and in the time we have taken to say this it had been in all the drawers in the nursery looking for Peters shadow rummaged the wardrobe and turned every pocket inside out It was not really a light it made this light by flashing about so quickly but when it came to rest for a second you saw it was a fairy no longer than your hand but still growing It was a girl called Tinker Bell exquisitely gowned in a skeleton leaf cut low and square through which her figure could be seen to the best advantage She was slightly inclined to embonpoint',
        'A moment after the fairys entrance the window was blown open by the breathing of the little stars and Peter dropped in He had carried Tinker Bell part of the way and his hand was still messy with the fairy dust',
        'Tinker Bell he called softly after making sure that the children were asleep Tink where are you She was in a jug for the moment and liking it extremely she had never been in a jug before',
        'Oh do come out of that jug and tell me do you know where they put my shadow',
        'The loveliest tinkle as of golden bells answered him It is the fairy language You ordinary children can never hear it but if you were to hear it you would know that you had heard it once before',
        'Tink said that the shadow was in the big box She meant the chest of drawers and Peter jumped at the drawers scattering their contents to the floor with both hands as kings toss hapence to the crowd In a moment he had recovered his shadow and in his delight he forgot that he had shut Tinker Bell up in the drawer',
        'If he thought at all but I dont believe he ever thought it was that he and his shadow when brought near each other would join like drops of water and when they did not he was appalled He tried to stick it on with soap from the bathroom but that also failed A shudder passed through Peter and he sat on the floor and cried',
        'His sobs woke Wendy and she sat up in bed She was not alarmed to see a stranger crying on the nursery floor she was only pleasantly interested',
        'Boy she said courteously why are you crying',
        'Peter could be exceeding polite also having learned the grand manner at fairy ceremonies and he rose and bowed to her beautifully She was much pleased and bowed beautifully to him from the bed',
        'Whats your name he asked',
        'Wendy Moira Angela Darling she replied with some satisfaction What is your name',
        'She was already sure that he must be Peter but it did seem a comparatively short name',
        'Yes he said rather sharply He felt for the first time that it was a shortish name',
        'Im so sorry said Wendy Moira Angela',
        'It doesnt matter Peter gulped',
        'She asked where he lived',
        'Second to the right said Peter and then straight on till morning',
        'What a funny address',
        'Peter had a sinking For the first time he felt that perhaps it was a funny address',
        'No it isnt he said',
        'I mean Wendy said nicely remembering that she was hostess is that what they put on the letters',
        'He wished she had not mentioned letters',
        'Dont get any letters he said contemptuously',
        'But your mother gets letters',
        'Dont have a mother he said Not only had he no mother but he had not the slightest desire to have one He thought them very overrated persons Wendy however felt at once that she was in the presence of a tragedy',
        'O Peter no wonder you were crying she said and got out of bed and ran to him',
        'I wasnt crying about mothers he said rather indignantly I was crying because I cant get my shadow to stick on Besides I wasnt crying',
        'It has come off',
        'Then Wendy saw the shadow on the floor looking so draggled and she was frightfully sorry for Peter How awful she said but she could not help smiling when she saw that he had been trying to stick it on with soap How exactly like a boy',
        'Fortunately she knew at once what to do It must be sewn on she said just a little patronisingly',
        'Whats sewn he asked',
        'But she was exulting in his ignorance I shall sew it on for you my little man she said though he was tall as herself and she got out her housewife and sewed the shadow on to Peters foot',
        'I daresay it will hurt a little she warned him',
        'Oh I shant cry said Peter who was already of the opinion that he had never cried in his life And he clenched his teeth and did not cry and soon his shadow was behaving properly though still a little creased',
        'Perhaps I should have ironed it Wendy said thoughtfully but Peter boylike was indifferent to appearances and he was now jumping about in the wildest glee Alas he had already forgotten that he owed his bliss to Wendy He thought he had attached the shadow himself How clever I am he crowed rapturously oh the cleverness of me',
        'It is humiliating to have to confess that this conceit of Peter was one of his most fascinating qualities To put it with brutal frankness there never was a cockier boy',
        'But for the moment Wendy was shocked You conceit she exclaimed with frightful sarcasm of course I did nothing',
        'You did a little Peter said carelessly and continued to dance',
        'A little she replied with hauteur if I am no use I can at least withdraw and she sprang in the most dignified way into bed and covered her face with the blankets',
        'To induce her to look up he pretended to be going away and when this failed he sat on the end of the bed and tapped her gently with his foot Wendy he said dont withdraw I cant help crowing Wendy when Im pleased with myself Still she would not look up though she was listening eagerly Wendy he continued in a voice that no woman has ever yet been able to resist Wendy one girl is more use than twenty boys',
        'Now Wendy was every inch a woman though there were not very many inches and she peeped out of the bedclothes',
        'Do you really think so Peter',
        'I think its perfectly sweet of you she declared and Ill get up again and she sat with him on the side of the bed She also said she would give him a kiss if he liked but Peter did not know what she meant and he held out his hand expectantly',
        'Surely you know what a kiss is she asked aghast',
        'I shall know when you give it to me he replied stiffly and not to hurt his feeling she gave him a thimble',
        'Now said he shall I give you a kiss and she replied with a slight primness If you please She made herself rather cheap by inclining her face toward him but he merely dropped an acorn button into her hand so she slowly returned her face to where it had been before and said nicely that she would wear his kiss on the chain around her neck It was lucky that she did put it on that chain for it was afterwards to save her life',
        'When people in our set are introduced it is customary for them to ask each others age and so Wendy who always liked to do the correct thing asked Peter how old he was It was not really a happy question to ask him it was like an examination paper that asks grammar when what you want to be asked is Kings of England',
        'I dont know he replied uneasily but I am quite young He really knew nothing about it he had merely suspicions but he said at a venture Wendy I ran away the day I was born',
        'Wendy was quite surprised but interested and she indicated in the charming drawingroom manner by a touch on her nightgown that he could sit nearer her',
        'It was because I heard father and mother he explained in a low voice talking about what I was to be when I became a man He was extraordinarily agitated now I dont want ever to be a man he said with passion I want always to be a little boy and to have fun So I ran away to Kensington Gardens and lived a long long time among the fairies',
        'She gave him a look of the most intense admiration and he thought it was because he had run away but it was really because he knew fairies Wendy had lived such a home life that to know fairies struck her as quite delightful She poured out questions about them to his surprise for they were rather a nuisance to him getting in his way and so on and indeed he sometimes had to give them a hiding Still he liked them on the whole and he told her about the beginning of fairies',
        'You see Wendy when the first baby laughed for the first time its laugh broke into a thousand pieces and they all went skipping about and that was the beginning of fairies',
        'Tedious talk this but being a stayathome she liked it',
        'And so he went on goodnaturedly there ought to be one fairy for every boy and girl',
        'Ought to be Isnt there',
        'No You see children know such a lot now they soon dont believe in fairies and every time a child says I dont believe in fairies there is a fairy somewhere that falls down dead',
        'Really he thought they had now talked enough about fairies and it struck him that Tinker Bell was keeping very quiet I cant think where she has gone to he said rising and he called Tink by name Wendys heart went flutter with a sudden thrill',
        'Peter she cried clutching him you dont mean to tell me that there is a fairy in this room',
        'She was here just now he said a little impatiently You dont hear her do you and they both listened',
        'The only sound I hear said Wendy is like a tinkle of bells',
        'Well thats Tink thats the fairy language I think I hear her too',
        'The sound came from the chest of drawers and Peter made a merry face No one could ever look quite so merry as Peter and the loveliest of gurgles was his laugh He had his first laugh still',
        'Wendy he whispered gleefully I do believe I shut her up in the drawer',
        'He let poor Tink out of the drawer and she flew about the nursery screaming with fury You shouldnt say such things Peter retorted Of course Im very sorry but how could I know you were in the drawer',
        'Wendy was not listening to him O Peter she cried if she would only stand still and let me see her',
        'They hardly ever stand still he said but for one moment Wendy saw the romantic figure come to rest on the cuckoo clock O the lovely she cried though Tinks face was still distorted with passion',
        'Tink said Peter amiably this lady says she wishes you were her fairy',
        'Tinker Bell answered insolently',
        'What does she say Peter',
        'He had to translate She is not very polite She says you are a great ugly girl and that she is my fairy',
        'He tried to argue with Tink You know you cant be my fairy Tink because I am an gentleman and you are a lady',
        'To this Tink replied in these words You silly ass and disappeared into the bathroom She is quite a common fairy Peter explained apologetically she is called Tinker Bell because she mends the pots and kettles',
        'They were together in the armchair by this time and Wendy plied him with more questions',
        'If you dont live in Kensington Gardens now',
        'Sometimes I do still',
        'But where do you live mostly now',
        'With the lost boys',
        'They are the children who fall out of their perambulators when the nurse is looking the other way If they are not claimed in seven days they are sent far away to the Neverland to defray expenses Im captain',
        'What fun it must be',
        'Yes said cunning Peter but we are rather lonely You see we have no female companionship',
        'Are none of the others girls',
        'Oh no girls you know are much too clever to fall out of their prams',
        'This flattered Wendy immensely I think she said it is perfectly lovely the way you talk about girls John there just despises us',
        'For reply Peter rose and kicked John out of bed blankets and all one kick This seemed to Wendy rather forward for a first meeting and she told him with spirit that he was not captain in her house However John continued to sleep so placidly on the floor that she allowed him to remain there And I know you meant to be kind she said relenting so you may give me a kiss',
        'For the moment she had forgotten his ignorance about kisses I thought you would want it back he said a little bitterly and offered to return her the thimble',
        'Oh dear said the nice Wendy I dont mean a kiss I mean a thimble',
        'Its like this She kissed him',
        'Funny said Peter gravely Now shall I give you a thimble',
        'If you wish to said Wendy keeping her head erect this time',
        'Peter thimbled her and almost immediately she screeched What is it Wendy',
        'It was exactly as if someone were pulling my hair',
        'That must have been Tink I never knew her so naughty before',
        'And indeed Tink was darting about again using offensive language',
        'She says she will do that to you Wendy every time I give you a thimble',
        'Again Tink replied You silly ass Peter could not understand why but Wendy understood and she was just slightly disappointed when he admitted that he came to the nursery window not to see her but to listen to stories',
        'You see I dont know any stories None of the lost boys knows any stories',
        'How perfectly awful Wendy said',
        'Do you know Peter asked why swallows build in the eaves of houses It is to listen to the stories O Wendy your mother was telling you such a lovely story',
        'Which story was it',
        'About the prince who couldnt find the lady who wore the glass slipper',
        'Peter said Wendy excitedly that was Cinderella and he found her and they lived happily ever after',
        'Peter was so glad that he rose from the floor where they had been sitting and hurried to the window',
        'Where are you going she cried with misgiving',
        'To tell the other boys',
        'Dont go Peter she entreated I know such lots of stories',
        'Those were her precise words so there can be no denying that it was she who first tempted him',
        'He came back and there was a greedy look in his eyes now which ought to have alarmed her but did not',
        'Oh the stories I could tell to the boys she cried and then Peter gripped her and began to draw her toward the window',
        'Let me go she ordered him',
        'Wendy do come with me and tell the other boys',
        'Of course she was very pleased to be asked but she said Oh dear I cant Think of mummy Besides I cant fly',
        'Oh how lovely to fly',
        'Ill teach you how to jump on the winds back and then away we go',
        'Oo she exclaimed rapturously',
        'Wendy Wendy when you are sleeping in your silly bed you might be flying about with me saying funny things to the stars',
        'And Wendy there are mermaids',
        'Oh cried Wendy to see a mermaid',
        'He had become frightfully cunning Wendy he said how we should all respect you',
        'She was wriggling her body in distress It was quite as if she were trying to remain on the nursery floor',
        'But he had no pity for her',
        'Wendy he said the sly one you could tuck us in at night',
        'None of us has ever been tucked in at night',
        'Oo and her arms went out to him',
        'And you could darn our clothes and make pockets for us None of us has any pockets',
        'How could she resist Of course its awfully fascinating she cried Peter would you teach John and Michael to fly too',
        'If you like he said indifferently and she ran to John and Michael and shook them Wake up she cried Peter Pan has come and he is to teach us to fly',
        'John rubbed his eyes Then I shall get up he said Of course he was on the floor already Hallo he said I am up',
        'Michael was up by this time also looking as sharp as a knife with six blades and a saw but Peter suddenly signed silence Their faces assumed the awful craftiness of children listening for sounds from the grownup world All was as still as salt Then everything was right No stop Everything was wrong Nana who had been barking distressfully all the evening was quiet now It was her silence they had heard',
        'Out with the light Hide Quick cried John taking command for the only time throughout the whole adventure And thus when Liza entered holding Nana the nursery seemed quite its old self very dark and you would have sworn you heard its three wicked inmates breathing angelically as they slept They were really doing it artfully from behind the window curtains',
        'Liza was in a bad temper for she was mixing the Christmas puddings in the kitchen and had been drawn from them with a raisin still on her cheek by Nanas absurd suspicions She thought the best way of getting a little quiet was to take Nana to the nursery for a moment but in custody of course',
        'There you suspicious brute she said not sorry that Nana was in disgrace They are perfectly safe arent they Every one of the little angels sound asleep in bed Listen to their gentle breathing',
        'Here Michael encouraged by his success breathed so loudly that they were nearly detected Nana knew that kind of breathing and she tried to drag herself out of Lizas clutches',
        'But Liza was dense No more of it Nana she said sternly pulling her out of the room I warn you if you bark again I shall go straight for master and missus and bring them home from the party and then oh wont master whip you just',
        'She tied the unhappy dog up again but do you think Nana ceased to bark Bring master and missus home from the party Why that was just what she wanted Do you think she cared whether she was whipped so long as her charges were safe Unfortunately Liza returned to her puddings and Nana seeing that no help would come from her strained and strained at the chain until at last she broke it In another moment she had burst into the diningroom of 27 and flung up her paws to heaven her most expressive way of making a communication Mr and Mrs Darling knew at once that something terrible was happening in their nursery and without a goodbye to their hostess they rushed into the street',
        'But it was now ten minutes since three scoundrels had been breathing behind the curtains and Peter Pan can do a great deal in ten minutes',
        'We now return to the nursery',
        'Its all right John announced emerging from his hidingplace I say Peter can you really fly',
        'Instead of troubling to answer him Peter flew around the room taking the mantelpiece on the way',
        'How topping said John and Michael',
        'How sweet cried Wendy',
        'Yes Im sweet oh I am sweet said Peter forgetting his manners again',
        'It looked delightfully easy and they tried it first from the floor and then from the beds but they always went down instead of up',
        'I say how do you do it asked John rubbing his knee He was quite a practical boy',
        'You just think lovely wonderful thoughts Peter explained and they lift you up in the air',
        'He showed them again',
        'Youre so nippy at it John said couldnt you do it very slowly once',
        'Peter did it both slowly and quickly Ive got it now Wendy cried John but soon he found he had not Not one of them could fly an inch though even Michael was in words of two syllables and Peter did not know A from Z',
        'Of course Peter had been trifling with them for no one can fly unless the fairy dust has been blown on him Fortunately as we have mentioned one of his hands was messy with it and he blew some on each of them with the most superb results',
        'Now just wiggle your shoulders this way he said and let go',
        'They were all on their beds and gallant Michael let go first He did not quite mean to let go but he did it and immediately he was borne across the room',
        'I flewed he screamed while still in midair',
        'John let go and met Wendy near the bathroom',
        'They were not nearly so elegant as Peter they could not help kicking a little but their heads were bobbing against the ceiling and there is almost nothing so delicious as that Peter gave Wendy a hand at first but had to desist Tink was so indignant',
        'Up and down they went and round and round Heavenly was Wendys word',
        'I say cried John why shouldnt we all go out',
        'Of course it was to this that Peter had been luring them',
        'Michael was ready he wanted to see how long it took him to do a billion miles But Wendy hesitated',
        'Mermaids said Peter again',
        'And there are pirates',
        'Pirates cried John seizing his Sunday hat let us go at once',
        'It was just at this moment that Mr and Mrs Darling hurried with Nana out of 27 They ran into the middle of the street to look up at the nursery window and yes it was still shut but the room was ablaze with light and most heartgripping sight of all they could see in shadow on the curtain three little figures in night attire circling round and round not on the floor but in the air',
        'Not three figures four',
        'In a tremble they opened the street door Mr Darling would have rushed upstairs but Mrs Darling signed him to go softly She even tried to make her heart go softly',
        'Will they reach the nursery in time If so how delightful for them and we shall all breathe a sigh of relief but there will be no story On the other hand if they are not in time I solemnly promise that it will all come right in the end',
        'They would have reached the nursery in time had it not been that the little stars were watching them Once again the stars blew the window open and that smallest star of all called out',
        'Then Peter knew that there was not a moment to lose Come he cried imperiously and soared out at once into the night followed by John and Michael and Wendy',
        'Mr and Mrs Darling and Nana rushed into the nursery too late The birds were flown',
      ],
    },
  ],
}
